### ISSUE TITLE
Example on how to do token refresh

### ISSUE THREAD

**Issue by beeman** [atulmy/oauth#4]
One thing that most endpoints require but that's not implemented in the examples yet is refreshing the tokens. 

I would be curious to see how one would go about and do that in this setup.

**Comment by atulmy** [comment]
If you are building only login/signup i.e. authentication flow using OAuth, you may not need to refresh the token. We are interested in getting user details and saving it into database.

However in case you want offline access and to call respective provider's API on behalf of user, then you will need to refresh the tokens periodically, which is kept out of the scope for this sample repository.

You can do following:
1. Save `refresh_token` along with user details like `name` and `email` in the database
2. Periodically run a cron job on server:
    1. Fetch all the users
    2. For each user, exchange `refresh_token` for new `access_token` and `refresh_token` via respective OAuth URL for refreshing token
    3. Save these new `refresh_token` and `access_token` for the user in database

For example, in case of [Google](https://developers.google.com/identity/protocols/oauth2/web-server#offline), refreshing token call would look like: 
```javascript
const user = await User.findOne()

const refresh = await axios({
  url: `https://oauth2.googleapis.com/token`,
  method: 'post',
  data: {
    client_id: OAUTH_GOOGLE_ID,
    client_secret: OAUTH_GOOGLE_SECRET,
    refresh_token: user.oauth.refresh_token,
    grant_type: 'refresh_token',
  },
})

if(refresh && refresh.data) {
  await User.updateOne({ _id: user._id }, { $set: { oauth: refresh.data } })
}
```

Hope this helps.

**Comment by beeman** [comment]
That helps a lot, thanks a lot for taking the time to answer this, I'm sure it will help others too.

Also thanks for making the scope of this app a bit clearer, I will start experimenting with refreshing tokens elsewhere. :)
