### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by mr-winson** [atulmy/oauth#8]
I think this would be a cool addition!

Docs:
https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter

**Comment by atulmy** [comment]
Hello @mr-winson, Twitter currently uses OAuth 1.0a protocol which is not quite similar to 2.0 and hence keeping out of the scope of this repository for now.

**Comment by atulmy** [comment]
Twitter OAuth 2.0 flow is now available https://github.com/atulmy/oauth#twitter
